config/routes.rb
Testapp::Application.routes.draw do
  get    'people'           => 'people#index', as: 'people'
  post   'people'           => 'people#create', as: 'create_person'
  get    'people/new'       => 'people#new', as: 'new_person'
  get    'people/:key/edit' => 'people#edit', as: 'edit_person'
  get    'people/:key'      => 'people#show', as: 'show_person'
  put    'people/:key'      => 'people#update', as: 'update_person'
  delete 'people/:key'      => 'people#destroy', as: 'delete_person'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
require 'hyperion/api'

class PeopleController < ApplicationController
  def index
    @people = Hyperion::API.find_by_kind(:people)
  end

  def show
    @person = Hyperion::API.find_by_key(params[:key])
  end

  def new
  end

  def edit
    @person = Hyperion::API.find_by_key(params[:key])
  end

  def create
    @person = Hyperion::API.save(params[:person].merge(kind: :people, created_at: Time.now, updated_at: Time.now))
    redirect_to show_person_path(@person[:key])
  end

  def update
    @person = Hyperion::API.find_by_key(params[:key])
    Hyperion::API.save(@person.merge(params[:person].merge(updated_at: Time.now)))
    redirect_to show_person_path(@person[:key])
  end

  def destroy
    @person = Hyperion::API.save(params[:person])
    redirect_to people_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= form_tag update_person_path(key: @person[:key]), method: :put do %>
  <%= text_field_tag('person[first_name]', @person[:first_name]) %>
  <%= text_field_tag('person[last_name]', @person[:last_name]) %>
  <%= submit_tag %>
<% end %>

<%= link_to 'Show', show_person_path(key: @person[:key]) %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person[:first_name] %></td>
    <td><%= person[:last_name] %></td>
    <td><%= person[:created_at] %></td>
    <td><%= person[:updated_at] %></td>
    <td><%= link_to 'Show', show_person_path(key: person[:key]) %></td>
    <td><%= link_to 'Edit', edit_person_path(key: person[:key]) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= form_tag create_person_path do %>
  <%= text_field_tag('person[first_name]') %>
  <%= text_field_tag('person[last_name]') %>
  <%= submit_tag %>
<% end %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<span>First Name: <%= @person[:first_name] %></span>
<span>Last Name: <%= @person[:last_name] %></span>

<%= link_to 'Edit', edit_person_path(key: @person[:key]) %> |
<%= link_to 'Back', people_path %>